import org.jetbrains.kotlin.gradle.targets.native.tasks.KotlinNativeTest

plugins {
    alias(libs.plugins.kotlinMultiplatform)
    alias(libs.plugins.kotlinxSerialization)

    alias(libs.plugins.maven.publish)

    alias(libs.plugins.kotest)
    alias(libs.plugins.ksp)
}

group = "io.github.julius-babies"
version = System.getenv("VERSION")?.ifBlank { null } ?: "unspecified"

repositories {
    mavenCentral()
}

kotlin {
    linuxX64()
    linuxArm64()
    macosArm64()
    mingwX64()

    applyDefaultHierarchyTemplate()

    sourceSets {
        nativeMain.dependencies {
            implementation(libs.kotlinxSerializationJson)

            implementation(libs.ktor.network)
            implementation(libs.ktor.client.core)
            implementation(libs.ktor.client.cio)
            implementation(libs.ktor.client.logging)
            implementation(libs.ktor.client.content.negotiation)
            implementation(libs.ktor.serialization.kotlinx.json)

            implementation(libs.kfile)
            implementation(libs.kommand)
        }

        macosMain.dependencies {
            implementation(libs.ktor.client.darwin)
        }

        linuxMain.dependencies {
            implementation(libs.ktor.client.curl)
        }

        mingwMain.dependencies {
            implementation(libs.ktor.client.winhttp)
        }

        nativeTest.dependencies {
            implementation(libs.kotest.framework.engine)
            implementation(libs.kotest.assertions.core)

            // Used by the tests to build and clean up their own temp directories.
            implementation(libs.kfile)
        }
    }

    compilerOptions {
        optIn.add("kotlin.time.ExperimentalTime")
        optIn.add("kotlin.io.encoding.ExperimentalEncodingApi")
    }
}

// Kotest's Kotlin/Native console reporter builds its terminal with a hardcoded
// AnsiLevel.TRUECOLOR and cannot detect that it runs inside an IDE (see the comment in Kotest's
// own invokeTestEngine.native.kt), so it always emits ANSI escapes - NO_COLOR and TERM are ignored.
// IntelliJ's test output pane prints those escapes verbatim, so filter them out of the test binary's
// stdout. The TeamCity service messages the IDE parses contain no escapes and pass through untouched.
val stripAnsiScript = layout.buildDirectory.file("kotest/strip-ansi.sh")

val stripAnsiWrapper = tasks.register("stripAnsiWrapper") {
    description = "Generates the wrapper that strips ANSI escapes from the Kotest console reporter."
    val script = stripAnsiScript
    outputs.file(script)
    doLast {
        val esc = "\u001B"
        script.get().asFile.apply {
            parentFile.mkdirs()
            writeText(
                """
                #!/bin/bash
                # Generated by docker-kt/build.gradle.kts - do not edit.
                binary="${'$'}1"
                shift
                # fflush keeps the output streaming so the IDE fills its test tree while tests run.
                "${'$'}binary" "${'$'}@" | awk '{ gsub(/$esc\[[0-9;?]*[a-zA-Z]/, ""); print; fflush() }'
                # Report the test binary's exit code, not awk's, so failing tests still fail the build.
                exit "${'$'}{PIPESTATUS[0]}"

                """.trimIndent()
            )
            setExecutable(true)
        }
    }
}

// bash and awk are not a given on a Windows host, and mingwX64Test only ever runs there.
if (!System.getProperty("os.name").startsWith("Windows")) {
    tasks.withType<KotlinNativeTest>().configureEach {
        dependsOn(stripAnsiWrapper)
        // Resolved during configuration: KotlinNativeTest.setExecutable reaches for Task.project,
        // which Gradle 10 forbids at execution time, so assign the backing property instead.
        val wrapper = objects.fileCollection().from(stripAnsiScript)
        doFirst {
            require(this is KotlinNativeTest)
            // Swapping the binary here rather than during configuration keeps the task's dependency
            // on the link task that produces it.
            args = listOf(executable.absolutePath) + args
            executableProperty.set(wrapper)
        }
    }
}

mavenPublishing {
    publishToMavenCentral()
    if (!gradle.startParameter.taskNames.any { it.contains("publishToMavenLocal") }) {
        signAllPublications()
    }
    coordinates(project.group.toString(), project.name, project.version.toString())

    pom {
        name = "docker.kt"
        description = "Docker.kt Kotlin/Native library for interacting with the Docker API"
        url = "https://github.com/Julius-Babies/docker.kt"

        developers {
            developer {
                id = "julius-vincent-babies"
                name = "Julius Vincent Babies"
                email = "julvin.babies@gmail.com"
                url = "https://github.com/Julius-Babies"
            }
        }

        scm {
            url = "https://github.com/Julius-Babies/docker.kt"
        }

        licenses {
            license {
                name = "The MIT License (MIT)"
                url = "https://opensource.org/license/MIT"
            }
        }
    }
}